### ISSUE TITLE
LSP inspector should listen to out channel documents instead of using web sockets

### ISSUE THREAD

**Issue by dbaeumer** [octref/vscode-lsp-inspector#1]
Using web sockets for streaming is pretty disruptive in terms of what clients need to do. Shouldn't the LSP Inspector extension be able to take a channel name and then simply listen on the document change events for the channel document. That would simplify things a lot.

**Comment by dbaeumer** [comment]
Testing https://github.com/Microsoft/vscode/issues/57310

**Comment by octref** [comment]
> Shouldn't the LSP Inspector extension be able to take a channel name and then simply listen on the document change events for the channel document.

How is that possible?

**Comment by octref** [comment]
I would love to make the process simpler — if the above is possible, please let me know how.

Meanwhile I don't think it's complicated to setup: https://github.com/Microsoft/vscode-extension-samples/commit/1c98dc232e3601aac9bf872a8e35c6327154af14#diff-52345968663124eb7bb34b94c13b77a5. By setting up WebSockets, this allows any Language Server extension author to use it (for example C++ which doesn't use our node lib: https://github.com/Microsoft/language-server-protocol-inspector/issues/30).

More details here: https://github.com/Microsoft/vscode/issues/57310#issuecomment-416601165

**Comment by dbaeumer** [comment]
To my knowledge an output channel is backed by a editor model and all models are synced into the extension host. But I can check if something has changed.

IMO the logging should only happen from the client side. The server should never directly write to a out of band web socket. We would be better off to have a special notification send from the server to the client to contain the trace data.

**Comment by dbaeumer** [comment]
Actually the notification exists in jsonrpc and is `$/logTraceNotification`

**Comment by dbaeumer** [comment]
So we might want to document this with our VS Code client so that servers using the VS Code client can make use of it.

**Comment by octref** [comment]
> So we might want to document this with our VS Code client so that servers using the VS Code client can make use of it.

Sure, I can add documentation and add it to CSS language feature.

**Comment by octref** [comment]
Also, I did it with `outputChannel` because I didn't find any API to listen to changes on channel output, or to query the list of available channels.

If we can have that API, I can certainly remove the WebSocket piece.
